{{- range $topic := .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic }}
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
  {{ end }}