---
# Source: kafka-resources/templates/kafka.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: account-creation.individual
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: account-creation.company
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: check-currency-price
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: deposit-money
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transfer-money
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
---
# Source: kafka-resources/templates/topic.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: withdraw-money
  labels:
    strimzi.io/cluster: "cluster"
spec:
  partitions: 1
  replicas: 1
